# Generated by Django 4.2 on 2023-04-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="hashtags",
        ),
        migrations.DeleteModel(
            name="Hashtag",
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
